# Generated by Django 5.0.3 on 2024-03-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0002_alter_task_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("In Progress", "In Progress"),
                    ("In Review", "In Review"),
                    ("On Hold", "On Hold"),
                    ("Resolved", "Resolved"),
                    ("Closed", "Closed"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
    ]
